[package]
name = "osui"
version = "0.0.5"
edition = "2021"
license = "Apache-2.0"
description = "A rsx TUI library"
repository = "https://github.com/osui-rs/osui"

[lib]
name = "osui"
path = "src/lib.rs"

[[bin]]
name = "osui"
path = "src/main.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
crossterm = "0.28.1"
regex = "1.11.1"
lazy_static = "1.4"
paste = "1.0.15"
osui-element = "0.1.0"
dyn-clone = "1.0.17"
