[package]
name = "osui"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
description = "A TUI library"

[lib]
name = "osui"
path = "src/lib.rs"

[[bin]]
name = "osui"
path = "src/main.rs"

[dependencies]
crossterm = "0.28.1"
