[package]
name = "osui"
version = "0.0.3"
edition = "2021"
license = "Apache-2.0"
description = "A TUI library"
repository = "https://github.com/orus-dev/osui"

[lib]
name = "osui"
path = "src/lib.rs"

[[bin]]
name = "osui"
path = "src/main.rs"

[dependencies]
crossterm = "0.28.1"
regex = "*"
lazy_static = "1.4"
paste = "1.0.15"